version: '3.8'

services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_container
    volumes:
      - mongodb_data:/data/db
      - ./dump:/dump
      - ./scripts:/scripts
    entrypoint: ["/scripts/mongo-entrypoint.sh"]
    ports:
      - "27017:27017"
    networks:
      - acordaosnet

  acordaosauth:
    build: ./Auth
    container_name: acordaosauth
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/acordaos
    depends_on:
      - mongodb_container
    restart: always
    ports:
      - "7777:7777"
    networks:
      - acordaosnet

  acordaosinterface:
    build: ./Interface
    container_name: acordaosInterface
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/acordaos
      - NODE_ENV=production
    depends_on:
      - mongodb_container
    restart: always
    ports:
      - "8888:8888"
    networks:
      - acordaosnet

  acordaosapi:
    build: ./API
    container_name: acordaosAPI
    environment:
      - MONGODB_URL=mongodb://mongodb_container:27017/acordaos
    depends_on:
      - mongodb_container
    restart: always
    ports:
      - "5555:5555"
    networks:
      - acordaosnet

networks:
  acordaosnet:
    driver: bridge

volumes:
  mongodb_data:
